### ISSUE TITLE
Is it possible to default to visualize the output of one process?

### ISSUE THREAD

**Issue by lucamug** [lydell/run-pty#35]
I use run-pty to run an elm-watch and an http server.

Would it be possible to automatically show the output of elm-watch wihtout the need of a manual selection?

The use case is a training class for children where I would like to system to start automatically, without the need to teach them how to reach the terminal and press [1].

Thanks.

**Comment by lydell** [comment]
Hi!

No, it’s not possible, and I’m not interested in adding support for it. You could fork run-pty though and easily add it yourself, I think.

Good luck with the training class!
