### ISSUE TITLE
Feature Request: Mouse click for "[ctrl+z] dashboard"

### ISSUE THREAD

**Issue by Strepto** [lydell/run-pty#37]
Hi, I like the design and looks of run-pty. 

I would like to be able to use the mouse to navigate back to "dashboard" after I have used a mouse click to `focus command`. 

![image](https://user-images.githubusercontent.com/3185998/215761082-65cd2108-e9bc-4176-94e6-06b36e7384b4.png)

I hoped this could be a quick fix as you already have mouse support, but if it does not fit the scope or you don't see the need feel free to close the issue.

**Comment by lydell** [comment]
HI! I would love to have this as well! But I don’t think it’s possible.

In terminals, you have to enable mouse mode to be able to do clicks. Then you get sort-of “events” which contain the coordinates of where a click was made. A side effect of that is that _scrolling_ is also changed. Normally, the terminal takes care of scrolling and lets you scroll back to look at older output. In mouse mode, you instead only get “events” about scrolling as well, and you are expected to implement scrolling yourself. Try for example `vim` – it does all of that. The problems with custom scrolling are:

1. It’s not easy to implement.
2. You’re then limited to one-line-at-a-time-scrolling. Many terminals have pixel-based smooth scrolling which is much nicer.
3. ctrl+f/cmd+f (search) breaks – the terminal doesn’t know of earlier output anymore so you can’t search for it.

**Comment by Strepto** [comment]
Ah, that makes sense! Thank you for a super quick response.

Feel free to close this issue, as I see the value of full the integrated "full" terminal support in the focus view.
