### ISSUE TITLE
Output breaks in Warp

### ISSUE THREAD

**Issue by natebrunette** [lydell/run-pty#38]
In the [Warp terminal](https://www.warp.dev/), It seems to only list the most recently finished command. Here's a sample config I reproduced the issue with to make sure there wasn't something specific in our project. I'm not sure if this is an issue with this library or with warp.

```json
[
  {
    "command": [
      "ls"
    ],
    "title": "list"
  },
  {
    "command": [
      "ls",
      "-la"
    ],
    "title": "list all"
  }
]
```

**Comment by lydell** [comment]
Hi! I don’t use Warp myself, but a colleague of mine does and last time we checked (very, very quickly though), it felt more the other way around – like Warp breaks run-pty. All other terminals I’ve tried – including the ancient cmd.exe – works fine.

**Comment by natebrunette** [comment]
@lydell thanks for the quick response. I can create an issue for Warp, but do you have any idea what specifically might be breaking in run-pty so I can narrow it down for them?

**Comment by lydell** [comment]
No idea right now. I screenshot _might_ give me a clue. But I probably need to install Warp to know something for sure. However, I don’t feel like doing so right now. I guess there’s a risk they won’t prioritize a not-very-popular npm package, so if you really want to see this fixed I encourage you to dive into the code of run-pty yourself to pinpoint what it is that Warp does not support / supports differently.

**Comment by natebrunette** [comment]
just wanted to updated and say that this started working somewhat recently.

**Comment by bardt** [comment]
I can confirm! moving selection with arrows doesn't work since it conflicts with Warp's navigation, but it is not a crucial feature and the rest of functionality it not broken. 🎉
