### ISSUE TITLE
Feature request - ability to receive JSON configuration from standard input

### ISSUE THREAD

**Issue by rokf** [lydell/run-pty#55]
Hello,

I was wondering if you've perhaps ever considered adding support for receiving the JSON configuration from standard input?

With that one could preprocess (i.e. concatenate or filter out some of the commands) the configuration file with something like https://jqlang.github.io/jq/ before piping it into `run-pty` without creating multiple configuration files for different variants beforehand.

Thanks!

**Comment by lydell** [comment]
Hi! run-pty already uses stdin: For listening to key strokes, and forwarding what you type to commands. I have tried reading the config from stdin before, but I have never managed to _both_ read config from stdin _and_ be an interactive app. I don’t think it’s possible. If you figure out how to do this, please let me know!

**Comment by rokf** [comment]
Makes sense, thank you for the explanation 👍
